//Boost Software License - Version 1.0 - August 17th, 2003
//
//Permission is hereby granted, free of charge, to any person or organization
//obtaining a copy of the software and accompanying documentation covered by
//this license (the "Software") to use, reproduce, display, distribute,
//execute, and transmit the Software, and to prepare derivative works of the
//Software, and to permit third-parties to whom the Software is furnished to
//do so, all subject to the following:
//
//The copyright notices in the Software and this entire statement, including
//the above license grant, this restriction and the following disclaimer,
//must be included in all copies of the Software, in whole or in part, and
//all derivative works of the Software, unless such copies or derivative
//works are solely in the form of machine-executable object code generated by
//a source language processor.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//DEALINGS IN THE SOFTWARE.
//Author: Ray de Kruif 2-07-2021

#ifndef V1OOPC_EXAMPLES_SCOREBOARD_HPP
#define V1OOPC_EXAMPLES_SCOREBOARD_HPP
#include "hwlib.hpp"
#include "../IPASS/TM1638_IPASS.hpp"

class scoreboard : public tm1638 {
protected:
    char standthuis = '0';
    char standuit = '0';
    hwlib::pin_in & knop1;
    hwlib::pin_in & knop2;
    hwlib::pin_in & knop3;
    hwlib::pin_in & knop4;

public:
    scoreboard(hwlib::pin_in & knop1, hwlib::pin_in & knop2,hwlib::pin_in & knop3,hwlib::pin_in & knop4, hwlib::pin_out & stb, hwlib::pin_out & clk, hwlib::pin_out & dio):
            tm1638(stb, clk, dio),
            knop1(knop1),
            knop2(knop2),
            knop3(knop3),
            knop4(knop4)

    {}

    void score();
};

#endif //V1OOPC_EXAMPLES_SCOREBOARD_HPP
