//Boost Software License - Version 1.0 - August 17th, 2003
//
//Permission is hereby granted, free of charge, to any person or organization
//obtaining a copy of the software and accompanying documentation covered by
//this license (the "Software") to use, reproduce, display, distribute,
//execute, and transmit the Software, and to prepare derivative works of the
//Software, and to permit third-parties to whom the Software is furnished to
//do so, all subject to the following:
//
//The copyright notices in the Software and this entire statement, including
//the above license grant, this restriction and the following disclaimer,
//must be included in all copies of the Software, in whole or in part, and
//all derivative works of the Software, unless such copies or derivative
//works are solely in the form of machine-executable object code generated by
//a source language processor.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//DEALINGS IN THE SOFTWARE.
//Author: Ray de Kruif 2-07-2021

#include "hwlib.hpp"
#include "TM1638_IPASS.hpp"
#include "../Scoreboard_IPASS/scoreboard.hpp"

int main() {
    namespace target = hwlib::target;

    //First display
    auto stb = target::pin_out(target::pins::d13);
    auto clk = target::pin_out(target::pins::d12);
    auto dio = target::pin_out(target::pins::d11);
    auto chip = tm1638(stb, clk, dio);

    //Second display
    auto stb2 = target::pin_out(target::pins::d14);
    auto clk2 = target::pin_out(target::pins::d15);
    auto dio2 = target::pin_out(target::pins::d16);
    auto chip2 = tm1638(stb2, clk2, dio2);

    //Third display
    auto stb3 = target::pin_out(target::pins::d7);
    auto clk3 = target::pin_out(target::pins::d6);
    auto dio3 = target::pin_out(target::pins::d5);
    auto knop1 = target::pin_in(target::pins::d4);
    auto knop2 = target::pin_in(target::pins::d3);
    auto knop3 = target::pin_in(target::pins::d2);
    auto knop4 = target::pin_in(target::pins::d17);
    auto chip3 = tm1638(stb3, clk3, dio3);
    auto chip3_2 = scoreboard(knop1, knop2,knop3,knop4, stb3, clk3, dio3);

    //chip3.everything_on();

    //lets go
    chip.activate();
    chip.clearall();
    chip.data(g1,l);
    chip.data(g2,e);
    chip.data(g3,t);
    chip.data(g4,s);
    chip.data(g6,g);
    chip.data(g7,o);

    //Teams demo
    chip2.clearall();
    chip2.data(g1,a);
    chip2.data(g2,j);
    chip2.data(g3,a);
    chip2.data(g4,min);
    chip2.data(g5,f);
    chip2.data(g6,e);
    chip2.data(g7,y);

    //Scoreboard
    chip3_2.clearall();
    chip3_2.score();
}
